apiVersion: v1
kind: Namespace
metadata:
  name: workers
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kajo-sa
  namespace: workers

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: workers
  name: kajo-role
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "watch", "list", "create", "delete"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: kajo-rolebinding
  namespace: workers
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: kajo-role
subjects:
  - kind: ServiceAccount
    name: kajo-sa
    namespace: workers

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kajo-api
  labels:
    app: kajo-api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: kajo-api
  template:
    metadata:
      labels:
        app: kajo-api
    spec:
      serviceAccountName: kajo-sa
      containers:
        - name: kajo-api
          image: kajo-api:dev-latest
          ports:
            - containerPort: 5050
---
apiVersion: v1
kind: Service
metadata:
  name: kajo-api
  labels:
    app: kajo-api
spec:
  selector:
    app: kajo-api
  ports:
    - protocol: TCP
      port: 80
