name: Release Docker Image

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'New Semantic Version'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - 
      name: Check out code
      uses: actions/checkout@v2

    - 
      name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    -
      name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: your-dockerhub-username/your-repo-name:${{ github.event.inputs.version }}
